### ISSUE TITLE
Document all Kaleidoscope hooks, with their inputs, outputs and hook points

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope#231] opened 2017-11-02 00:02 UTC
Basically, the API for plugins needs a writeup.

**Comment by gedankenexperimenter** [comment] 2017-11-02 04:17
I'd label this as "bug" and "docs" as requested, but I don't have permission to do that.

**Comment by cdisselkoen** [comment] 2017-11-04 04:56
This is also essentially a duplicate of #169.

**Comment by algernon** [comment] 2017-11-04 05:49
...that indeed it is. Added the labels there, and am closing this one.

**Closed** 2017-11-04 05:49 UTC
Labels: bug, docs, duplicate
