### ISSUE TITLE
Active modifier LED highlight doesn't work all for the first ~minute after boot

### ISSUE THREAD

**Issue by wearpants** [keyboardio/Kaleidoscope#670] opened 2019-07-31 00:54 UTC
Using OneShot mode, the active modifier LED plugin doesn't highlight any keys for the first minute or so after boot, even though the modifiers work properly.

Might be the first few dozen keypresses rather than time-based.

**Comment by gedankenexperimenter** [comment] 2019-07-31 04:07
My guess is that it's being overridden by the BootGreeting effect.

**Comment by algernon** [comment] 2019-07-31 06:26
I asked @wearpants on Discord, and he confirmed: if one changes layers, the highlight will work after that. The problem is caching. `ActiveModColor` will scan the keymap on setup and at layer change. For some reason, the scan on setup doesn't yield the results we want.

**Comment by algernon** [comment] 2019-08-16 17:20
I _think_ I have a fix for this, a simple one too. Unfortunately, while trying to verify if it really works, I discovered that ActiveModColor doesn't seem to restore the original color. Not sure whether that's an ActiveModColor or a Colormap issue yet, though.

**Closed** 2019-08-16 18:43 UTC
Labels: bug, leds, plugin
