### ISSUE TITLE
OneShot: Very short keypress does not trigger OneShot

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#418] opened 2018-10-18 06:12 UTC
Originally by @Phlogistique, as keyboardio/Kaleidoscope-OneShot#36.

**Comment by algernon** [comment] 2018-10-21 16:09
@Phlogistique, can you check if this issue still presists with the current git master of Kaleidoscope? I noticed the same problem before, but after #437, I do not see it anymore.

**Comment by gedankenexperimenter** [comment] 2020-10-04 23:58
I'm pretty sure this has been fixed. I'm even more certain that it's not a bug in #905.

**Comment by obra** [comment] 2020-10-05 01:20
Closing as obsolete. @Phlogistique - if this is still an issue, please feel free to re-open.

**Closed by obra** 2020-10-05 01:20 UTC
Labels: bug, pending, plugin:oneshot
