### ISSUE TITLE
Qukeys: ShiftToLayer with setReleaseDelay makes layer stick

### ISSUE THREAD

**Issue by davidaue** [keyboardio/Kaleidoscope#501] opened 2018-12-16 00:21 UTC
Give cmd key a qukey for shift to the function layer.
Set a long release delay so rollover behavior is easy to reproduce.

    Qukeys.setReleaseDelay(200);
    QUKEYS(
      kaleidoscope::Qukey(0, 0, 7, ShiftToLayer(FUNCTION)),
    )

Quickly execute rollover for '{':

    cmd down
    U down
    cmd up
    U up

'{' is produced as expected from release delay behavior
Pressing U again produces '{' indicating function layer is still selected.

**Comment by gedankenexperimenter** [comment] 2018-12-16 06:19
I have a fix for the problem, but it's not actually in Qukeys. Instead, it would change `handleKeyswitchEvent()` so that, if it gets passed a non-default `mappedKey` value, it uses that value to update `liveCompositeKeymap` instead of doing a keymap lookup.

I'll submit a PR tomorrow or Monday with this proposed change, but although it's only a few lines of code, it's a much more serious change to Kaleidoscope than a mere plugin fix, so it will require some real scrutiny before being merged (head's up, @algernon).

It's possible that there's another way to make layer-change qukeys work properly, but I haven't got any other ideas at the moment.

**Comment by gedankenexperimenter** [comment] 2018-12-17 16:15
Before I submit a PR, here's an excessively detailed explanation of what's going on.

Suppose we have the following Qukey defined (base layer, key <kbd>P</kbd>):
```
kaleidoscope::Qukey(0, 1, 14, Key_LeftShift)
```
Then the following sequence of events happens:

1. We press the key <kbd>P</kbd>.
2. `handleKeyswitchEvent()` calls `Layer.updateLiveCompositeKeymap(1, 14)` by looking up the row and column in the keymap, where it finds `Key_P`. Now `Layer.liveCompositeKeymap[1][14]` contains `Key_P`.
3. Qukeys consumes this event, adding it to the `key_queue`, and no output is generated.
4. We press the key <kbd>U</kbd>.
5. Qukeys adds that event to the `key_queue`. No output.
6. We release <kbd>U</kbd>.
7. Qukeys sets the keycode for the qukey to it's alternate `Key` value (`Key_LeftShift`), and calls `handleKeyswitchEvent(Key_LeftShift, 1, 14, IS_PRESSED)`.
8. Once again, `Layer.updateLiveCompositeKeymap(1, 14)` is called, setting `liveCompositeKeymap[1][14]` to `Key_P`.
9. Because we specified a `mappedKey`, the value in `liveCompositeKeymap` doesn't get used, and `Key_LeftShift` is what gets added to the ensuing report.
10. Qukeys calls `handleKeyswitchEvent()` again to flush the <kbd>U</kbd> from `key_queue`.
11. `Key_U` gets added to the report, and the output is `U` (with shift).
12. Qukeys makes another call to `handleKeyswitchEvent()` is made, sending the release of <kbd>U</kbd>.
13. In the next scan cycle, <kbd>P</kbd> is still pressed, causing a call to `handleKeyswitchEvent(Key_NoKey, 1, 14, IS_PRESSED | WAS_PRESSED)`. `Layer.updateLiveKeymap()` does not get called this time, because `keyToggledOn(IS_PRESSED | WAS_PRESSED)` is `false`.
14. Qukeys recognizes that <kbd>P</kbd> is a qukey, because its coordinates match, and `Layer.lookupActiveLayer(1, 14)` is `0` (the base layer). It therefore changes `mappedKey` from `Key_F` to `Key_LeftShift`, and there's no change in the ensuing report.

That all works as intended. The trouble comes if we instead have this qukey defined:
```
kaleidoscope::Qukey(0, 1, 14, ShiftToLayer(FUNCTION))
```

Here's what happens with the same sequence of events:

1. We press the key <kbd>P</kbd>.
2. `handleKeyswitchEvent()` calls `Layer.updateLiveCompositeKeymap(1, 14)` by looking up the row and column in the keymap, where it finds `Key_P`. Now `Layer.liveCompositeKeymap[1][14]` contains `Key_P`.
3. Qukeys consumes this event, adding it to the `key_queue`, and no output is generated.
4. We press the key <kbd>U</kbd>.
5. Qukeys adds that event to the `key_queue`. No output.
6. We release <kbd>U</kbd>.
7. Qukeys sets the keycode for the qukey to it's alternate `Key` value (`ShiftToLayer(FUNCTION)`), and calls `handleKeyswitchEvent(ShiftToLayer(FUNCTION), 1, 14, IS_PRESSED)`.
8. Once again, `Layer.updateLiveCompositeKeymap(1, 14)` is called, setting `liveCompositeKeymap[1][14]` to `Key_P`.
9. Because `mappedKey` is a layer shift, `Layer.eventHandler()` activates the `FUNCTION` layer, and returns `Key_NoKey`. No output change.
10. Qukeys calls `handleKeyswitchEvent()` again to flush the <kbd>U</kbd> from `key_queue`.
11. `handleKeyswitchEvent()` is called, but now that the `FUNCTION` layer is active, <kbd>U</kbd> is looked up, and `Layer.liveCompositeKeymap[1][11]` becomes `Key_LeftCurlyBracket`. This is added to the report, and the output is `{`.
12. Qukeys makes another call to `handleKeyswitchEvent()` is made, sending the release of <kbd>U</kbd>.
13. In the next scan cycle, <kbd>P</kbd> is still pressed, causing a call to `handleKeyswitchEvent(Key_NoKey, 1, 14, IS_PRESSED | WAS_PRESSED)`. `Layer.updateLiveKeymap()` does not get called this time, because `keyToggledOn(IS_PRESSED | WAS_PRESSED)` is `false`. `mappedKey` looked up in `Layer.liveCompositeKeymap[1][14]`, and becomes `Key_P`.
14. Qukeys sees that the key that is held has coordinates `(2, 1, 14)` (<kbd>P</kbd> on the `FUNCTION` layer). This is not a qukey, so it does not change `mappedKey` from `Key_P` to `ShiftToLayer(FUNCTION)`. `Key_P` gets added to the report, and the output is `p`. If we keep holding <kbd>P</kbd>, it will repeat.
14. We release <kbd>P</kbd>.

At this point, no keys are held, but the `FUNCTION` layer is still active. Any keys pressed will be mapped from that layer (including <kbd>P</kbd>, which now produces `]`). This is because there was no point at which we called `handleKeyswitchEvent()` to indicate that a `ShiftToLayer(FUNCTION)` key was *toggled off*. Because of the way the scan cycle works, `ShiftToLayer` keys only do something when they are toggled on or off, not when they're held. This makes them somewhat fragile, and susceptible to causing layers to get stuck on when plugins do unexpected/incorrect things.

Note that this bug is not a problem for DualUse layer-shift definitions in the keymap, but those are more limited since the primary key cannot have modifiers applied (among other things).

I'll submit a PR with a solution to the problem shortly.

**Comment by davidaue** [comment] 2018-12-18 16:00
I applied your changes to layers.h and key_events.cpp but am still seeing the same behavior with the rollover sticking the layer.

**Comment by gedankenexperimenter** [comment] 2018-12-18 16:46
Aha! There is, in fact, a way to get a layer shift stuck with release delay rollover that I hadn't seen before. I stand corrected, and will search for a solution today.

I would like to point out two things, however:

1. `R0C7` is <kdb>ctrl</kbd> on the standard QWERTY layout, not <kbd>cmd</kbd>.
2. A qukey with a primary key value of `Key_LeftGui` (or any other modifier) doesn't make much sense. Was this just defined for demonstrating the rollover bug, or do you have some use for it?

**Comment by davidaue** [comment] 2018-12-18 17:07
I must have swapped my ctrl and cmd caps at some point and forgot about it. That key on my layout is left paren with a qukey for a layer shift. 

My actual setup is a bit complicated with separate function layers depending on if you layer shifted with the left or right hand, affecting what other qukeys are active for chording. So yes, it was just a dummy example for repro simplicity.

**Comment by gedankenexperimenter** [comment] 2018-12-18 19:59
I have a fix that appears to work, but it's pretty ugly. I'll try to combine it with other changes that cut out the code made obsolete by the more general layer-change fix, and base it off of that other PR.

**Comment by gedankenexperimenter** [comment] 2018-12-19 01:35
@davidaue: Please try out the changes in #505; I believe that should fix the rollover problem (as well as the basic layer-shift problem).

**Closed** 2019-03-28 00:14 UTC
